services:
  aidetector:
    image: "ghcr.io/eschouten/ai-detector:latest"

    volumes:
      - ./config.json:/app/config.json
      - ./sprong24.mp4:/app/sprong24.mp4
      - ./detections/:/app/detections

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
