services:
  aidetector:
    image: "ghcr.io/eschouten/ai-detector:latest"
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

    volumes:
      - ./example/config.json:/app/config.json
      - ./example/app.json:/app/app.json
      - ./example/sprong24.mp4:/app/sprong24.mp4
      - ./example/detections/:/app/detections
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  web:
    image: "ghcr.io/eschouten/ai-detector-web:latest"
    depends_on:
      - aidetector
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "80:3000"
    volumes_from:
      - aidetector
