services:
  aidetector:
    # Build the image from the Dockerfile in the current directory
    build: detector

    volumes:
      - ./example/config.json:/app/config.json:ro
      - ./example/sprong24.mp4:/app/sprong24.mp4:ro
      - ./example/detections/:/app/detections
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
