export const WEBRTC_PREVIEW_ICE_SERVERS = [] as const;

export const WEBRTC_PREVIEW_FIRST_FRAME_TIMEOUT_MS = 10_000;
export const WEBRTC_PREVIEW_NO_FRAME_TIMEOUT_MS = 8_000;
export const WEBRTC_PREVIEW_FORCE_KILL_DELAY_MS = 2_000;
export const WEBRTC_PREVIEW_SESSION_IDLE_TIMEOUT_MS = 30_000;
export const WEBRTC_PREVIEW_ICE_GATHERING_TIMEOUT_MS = 1_500;
export const WEBRTC_PREVIEW_REBUILD_DEBOUNCE_MS = 200;
export const WEBRTC_PREVIEW_RECONNECT_DELAY_MS = 2_000;
export const WEBRTC_PREVIEW_H264_PAYLOAD_TYPE = 96;
export const WEBRTC_PREVIEW_FPS = 8;
export const WEBRTC_PREVIEW_MAX_WIDTH = 640;
export const WEBRTC_PREVIEW_RTP_PACKET_SIZE = 1_200;
export const WEBRTC_PREVIEW_SESSION_PATH = '/streams/webrtc/session';
